In [5]:
# Que.1 - Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each method and the final output after each method.


# Method - 1 : Using numpy.array with a nested list
import numpy as np

# Creating a 2D array using a nested list
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array created using numpy.array with a nested list:")
print(array1)


# Method - 2 : Using numpy.zeros and setting values manually

# Creating a 2D array using numpy.zeros and then setting values
array2 = np.zeros((2, 3), dtype=int)
array2[0, 0] = 1
array2[0, 1] = 2
array2[0, 2] = 3
array2[1, 0] = 4
array2[1, 1] = 5
array2[1, 2] = 6

print("\nArray created using numpy.zeros and setting values manually:")
print(array2)


# Method - 3 : Using numpy.full and slicing


# Creating a 2D array using numpy.full and slicing
array3 = np.full((2, 3), 0)
array3[0, :] = [1, 2, 3]
array3[1, :] = [4, 5, 6]

print("\nArray created using numpy.full and slicing:")
print(array3)


Array created using numpy.array with a nested list:
[[1 2 3]
 [4 5 6]]

Array created using numpy.zeros and setting values manually:
[[1 2 3]
 [4 5 6]]

Array created using numpy.full and slicing:
[[1 2 3]
 [4 5 6]]


In [7]:
# Que.2 - Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1-D array into a 2-D array.

# Solving


# 1. Define the parameters
start = 1      # Starting value of the sequence
end = 10       # Ending value of the sequence
num_values = 100  # Number of evenly spaced numbers

# 2. Generate a 1D array of evenly spaced numbers
array_1d = np.linspace(start, end, num_values)

# Reshape the 1D array into a 2D array
# To reshape into a 2D array, we need to make sure that the total number of elements matches the product of the new dimensions. For example, 100 elements can be reshaped into (10, 10).
num_rows = 10
num_cols = 10

array_2d = array_1d.reshape(num_rows, num_cols)

# Print the resulting 2D array
print("2D array after reshaping:")
print(array_2d)


2D array after reshaping:
[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.0909

In [32]:
# Que.3 -  Explain the following terms.

# [a]. The difference in np.array, np.asarray and np.asanyarray.
# [b]. The difference between Deep copy and shallow copyX




# [a]. The difference in np.array, np.asarray and np.asanyarray



# np.array - It is use to create a new array.
# Using np.array

list1 = [1,2,3]
array1 = np.array(list1)
print("Using np.array :",array1)


# np.asarray - it is used to convert the input to ndarray, but it does not copy the data if the input is already in ndarray.
# Using np.asarray

array2 = np.asarray(list1)
print("Using np.asarray :",array2)

# np.asanyarray - it is similar as np.asarray but it passes the through subclasses of 'ndarray'(such as matrix). it ensure that the result is subclass
# Using np.asanyarray

array3 = np.asanyarray(list1)
print("Using np.asanyarray:",array3)




print("")




# [b]. The Differcence between Deep copy and shallow copy.




#  Deep Copy - A Deep copy create a new array object and a new copy of the data , so changed in one do not affect other.

# Deep copy example -

original_array = np.array([1,2,3])
deep_copy = original_array.copy()
deep_copy[0] = 99 
print("original array after modifying deep_copy :",original_array)
print("Deep_copy :",deep_copy)


# Shallow Copy - A Shallow copy create a new array object but it share the data with original array, so change in one affect other.
print("")


original_array2 = np.array([4,5,6])
shallow_copy = original_array2
shallow_copy[0] = 999
print("original array after modifying shallow_copy :",original_array2)
print("Shallow_copy :",shallow_copy)

Using np.array : [1 2 3]
Using np.asarray : [1 2 3]
Using np.asanyarray: [1 2 3]

original array after modifying deep_copy : [1 2 3]
Deep_copy : [99  2  3]

original array after modifying shallow_copy : [999   5   6]
Shallow_copy : [999   5   6]
