In [98]:
# Que.1 - Demonstrate three different methods for creating identical 2D arrays in NumPy, Provide the code for each method and the final output after each method.


# Method - 1 : Using numpy.array with a nested list
import numpy as np

# Creating a 2D array using a nested list
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array created using numpy.array with a nested list:")
print(array1)


# Method - 2 : Using numpy.zeros and setting values manually

# Creating a 2D array using numpy.zeros and then setting values
array2 = np.zeros((2, 3), dtype=int)
array2[0, 0] = 1
array2[0, 1] = 2
array2[0, 2] = 3
array2[1, 0] = 4
array2[1, 1] = 5
array2[1, 2] = 6

print("\nArray created using numpy.zeros and setting values manually:")
print(array2)


# Method - 3 : Using numpy.full and slicing


# Creating a 2D array using numpy.full and slicing
array3 = np.full((2, 3), 0)
array3[0, :] = [1, 2, 3]
array3[1, :] = [4, 5, 6]

print("\nArray created using numpy.full and slicing:")
print(array3)


Array created using numpy.array with a nested list:
[[1 2 3]
 [4 5 6]]

Array created using numpy.zeros and setting values manually:
[[1 2 3]
 [4 5 6]]

Array created using numpy.full and slicing:
[[1 2 3]
 [4 5 6]]


In [99]:
# Que.2 - Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1-D array into a 2-D array.

# Solving


# 1. Define the parameters
start = 1      # Starting value of the sequence
end = 10       # Ending value of the sequence
num_values = 100  # Number of evenly spaced numbers

# 2. Generate a 1D array of evenly spaced numbers
array_1d = np.linspace(start, end, num_values)

# Reshape the 1D array into a 2D array
# To reshape into a 2D array, we need to make sure that the total number of elements matches the product of the new dimensions. For example, 100 elements can be reshaped into (10, 10).
num_rows = 10
num_cols = 10

array_2d = array_1d.reshape(num_rows, num_cols)

# Print the resulting 2D array
print("2D array after reshaping:")
print(array_2d)


2D array after reshaping:
[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.0909

In [100]:
# Que.3 -  Explain the following terms.

# [a]. The difference in np.array, np.asarray and np.asanyarray.
# [b]. The difference between Deep copy and shallow copyX




# [a]. The difference in np.array, np.asarray and np.asanyarray



# np.array - It is use to create a new array.
# Using np.array

list1 = [1,2,3]
array1 = np.array(list1)
print("Using np.array :",array1)


# np.asarray - it is used to convert the input to ndarray, but it does not copy the data if the input is already in ndarray.
# Using np.asarray

array2 = np.asarray(list1)
print("Using np.asarray :",array2)

# np.asanyarray - it is similar as np.asarray but it passes the through subclasses of 'ndarray'(such as matrix). it ensure that the result is subclass
# Using np.asanyarray

array3 = np.asanyarray(list1)
print("Using np.asanyarray:",array3)




print("")




# [b]. The Differcence between Deep copy and shallow copy.




#  Deep Copy - A Deep copy create a new array object and a new copy of the data , so changed in one do not affect other.

# Deep copy example -

original_array = np.array([1,2,3])
deep_copy = original_array.copy()
deep_copy[0] = 99 
print("original array after modifying deep_copy :",original_array)
print("Deep_copy :",deep_copy)


# Shallow Copy - A Shallow copy create a new array object but it share the data with original array, so change in one affect other.
print("")


original_array2 = np.array([4,5,6])
shallow_copy = original_array2
shallow_copy[0] = 999
print("original array after modifying shallow_copy :",original_array2)
print("Shallow_copy :",shallow_copy)

Using np.array : [1 2 3]
Using np.asarray : [1 2 3]
Using np.asanyarray: [1 2 3]

original array after modifying deep_copy : [1 2 3]
Deep_copy : [99  2  3]

original array after modifying shallow_copy : [999   5   6]
Shallow_copy : [999   5   6]


In [101]:
# Que.4 - Generate a 3x3 array with random floating-point numbers between 5 and 20. then, round each number in the array to 2 decimal places.

# Solve >>

# Step 1. Generaing 3*3 array with random floating-point numbers between 5 to 20.
random_arr = np.random.uniform(5,20,(3,3))

# Step 2. Rounding each number in the array to 2 decimal places.
round_arr = np.round(random_arr,2)


print("Random_array  :")
print(random_arr)
print("Round_Array  :")
print(round_arr)

Random_array  :
[[18.44814201 10.0961014  18.05943266]
 [ 8.37216213 13.83407983 11.23022725]
 [16.0556957  16.54468004  6.81920273]]
Round_Array  :
[[18.45 10.1  18.06]
 [ 8.37 13.83 11.23]
 [16.06 16.54  6.82]]


In [102]:
# Que.5 - Create a NumPy array with random integers Between 1 and 10 of shape (5,6). After creating the array perform the following operations:

 # a). Extract all even integers from array.

 # b). Extract all odd integers from array.
 
 
 
# Solving : 

Random_arr = np.random.randint(1,11,(5,6)) # I chose np.random.randint(1, 11, (5, 6)) to generate random integers between 1 and 10 because the upper bound in np.random.randint is exclusive. This means that np.random.randint(1, 11, (5,6)) will generate integers from 1 up to 10, inclusive.
print("\nRandom Array of (5,6):")
print(Random_arr)
print("")

# a). Extracting all even number from array

Even_number = Random_arr[Random_arr % 2 == 0]
print("Even Number :")
print(Even_number)


# b). Extracting all odd Integer from array

odd_number = Random_arr[Random_arr % 2 != 0]
print("odd number :")
print(odd_number)


Random Array of (5,6):
[[ 4  7  4  7  8  4]
 [ 9  8  2  9  6  6]
 [ 1 10  9  2  8  1]
 [ 1  8  7  5  3  7]
 [ 9  4  7  5  1  5]]

Even Number :
[ 4  4  8  4  8  2  6  6 10  2  8  8  4]
odd number :
[7 7 9 9 1 9 1 1 7 5 3 7 9 7 5 1 5]


In [103]:
# Que.6 - Create a 3D NumPy array of shape (3, 3, 3) containing random integers Between 1 and 10. Perform the following operations:

 # a). Find the indices of the maximum values along each depth level (third axis).

 # b). Perform element wise multiplication of between both array
 
 
 
 # Creating 3D numpy array of shape (3,3,3) containing random integer between 1 to 10
random_np_arr = np.random.randint(1,11,(3,3,3))
print("\nGenerating random array of shape(3,3,3) :")
print(random_np_arr)
print("")


# b). Find the indices of the msximum values along each depth level (Third axis)
max_indices = np.argmax(random_np_arr, axis=2)
print("\n(a) Indices of the maximum value along each depth level(third axis) :")
print(max_indices)


# c). Performing element wise multiplication of between both array
random_np_arr2 = np.random.randint(1,11,(3,3,3)) # Creating second 3d array

# Perform element wise multiplication
result_arr = random_np_arr * random_np_arr2
print("\n(b) Result array after element wise multiplication")
print(result_arr)




Generating random array of shape(3,3,3) :
[[[2 4 8]
  [4 8 9]
  [1 9 6]]

 [[3 2 6]
  [9 9 6]
  [1 7 1]]

 [[7 7 9]
  [6 2 6]
  [1 6 5]]]


(a) Indices of the maximum value along each depth level(third axis) :
[[2 2 1]
 [2 0 1]
 [2 0 1]]

(b) Result array after element wise multiplication
[[[ 8  8 64]
  [ 4 16 36]
  [ 5 90 30]]

 [[24  2 30]
  [63 27 60]
  [ 6 63  6]]

 [[21 28 54]
  [54 20 42]
  [ 1 60 40]]]


In [104]:
import pandas as pd

## Que. 7
### Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attriButes and data types of each column.

In [110]:
# Que 8. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.


df = pd.read_csv(r"E:\DataScience\Assignment\People Data.csv")
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Index          1000 non-null   int64 
 1   User Id        1000 non-null   object
 2   First Name     1000 non-null   object
 3   Last Name      1000 non-null   object
 4   Gender         1000 non-null   object
 5   Email          1000 non-null   object
 6   Phone          979 non-null    object
 7   Date of birth  1000 non-null   object
 8   Job Title      1000 non-null   object
 9   Salary         1000 non-null   int64 
dtypes: int64(2), object(8)
memory usage: 78.3+ KB


Here the Dtypes of Phone column is object. So checking unwanted value and just drop it.

In [106]:
df['Phone'].unique()

array(['857.139.8239', nan, '(599)782-0605', '(390)417-1635x3010',
       '8537800927', '093.655.7480x7895', '4709522945', '013.820.4758',
       '(560)903-5068x4985', '8629884096', '+1-041-859-3844x272',
       '801.809.9181x37308', '+1-511-127-6660x230', '903.545.8947',
       '(416)979-0633x058', '244-054-8521x1913', '(929)366-8549x3587',
       '(973)243-9193', '060-611-9377x90160', '601.838.8295x89942',
       '668.063.9568x7257', '(590)187-8007x273', '972.064.3833x5347',
       '(614)275-6966x22597', '(322)679-7824', '989.482.6130x996',
       '975-190-7875x3293', '(291)853-7982x0123', '(984)863-5741x7054',
       '(977)846-8023', '526-208-4712x10329', '157.425.5345',
       '600-706-8696x839', '557-620-5663', '000-364-9407x55677',
       '(116)776-0713x4684', '+1-932-606-8425x22206', '341.096.2708x237',
       '+1-833-716-3269x028', '001-313-023-3603x2485',
       '001-366-475-8607x04350', '(412)388-9715', '353.983.3416',
       '355-371-5885x826', '+1-326-669-0118x4341',
      

In [107]:
# filterig all string column and just dropping
df_copy = df.copy() #copying dataset in df_copy 
df_copy['Phone'] = df_copy['Phone'].fillna('0000000000') # Here is some value is null so we filling with 000000000
df_copy[~df_copy.Phone.str.isnumeric()] # Checkig all string value

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
6        7  efeb05c7Cc94EA3     Ernest   Hoffman    Male   
8        9  421fAB9a3b98F30     Cheryl      Mays    Male   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                       Email                  Phone Date of birth  \
0        pwarner@example.org           857.139.8239    27-01-2014   
2        fhoward@example.org          (599)782-0605    25-11-2013   
4           elin@example.net     (390)417-1635x3010    15-04-1923   
6     jeffharvey@example.com      093.655.7480x7895    22-12-1984   
8         jake50@example.com           013.820.4758    16-12-2012   
..                       ...                    ...           ...   
995   lyonsdaisy@example.net           021.775.2933    05-01-1959   
996  dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997   georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998      wanda04@example.net          (915)292-2254    31-08-1971   
999  deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
2                               Copy   50000  
4                Biomedical engineer  100000  
6                     Health visitor   60000  
8               Designer, multimedia   50000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[905 rows x 10 columns]

In [109]:
df_copy['Phone'] = df_copy['Phone'].str.replace("."," ").str.replace("+"," ").str.replace("-"," ").str.replace("x","").str.replace(" ","")
# Clean the 'Phone' column
df_copy['Phone'] = df_copy['Phone'].str.replace(r'\D', '', regex=True)

# Convert the 'Phone' column to float
df_copy['Phone'] = df_copy['Phone'].astype(float)

# Display the cleaned DataFrame
print("\nDataFrame after cleaning and converting 'Phone' column to float:")
print(df_copy)

# Display table attributes and data types of each column
print("\nTable Attributes and Data Types:")
print(df_copy.info())


DataFrame after cleaning and converting 'Phone' column to float:
     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email         Phone Date of birth  \
0              pwarner@example.org  8.571398e+09    27-01-2014   
1    fergusonkatherine@example.net  0.000000e+00    26-07-1931   
2              

## Que .8- Perform the following tasks using people dataset:

 a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 values

In [125]:

# a) Read the 'data.csv' file using pandas, skipping the first 50 rows
df = pd.read_csv(r"E:\DataScience\Assignment\People Data.csv", skiprows = 50) #skiprows=range(1, 51))
df

50  afF3018e9cdd1dA     George    Mercer  Female  \
0      51  CccE5DAb6E288e5         Jo    Zavala    Male   
1      52  DfBDc3621D4bcec     Joshua     Carey  Female   
2      53  f55b0A249f5E44D     Rickey     Hobbs  Female   
3      54  Ed71DcfaBFd0beE      Robyn    Reilly    Male   
4      55  FDaFD0c3f5387EC  Christina    Conrad    Male   
..    ...              ...        ...       ...     ...   
945   996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
946   997  ECddaFEDdEc4FAB      Donna     Barry  Female   
947   998  2adde51d8B8979E      Cathy  Mckinney  Female   
948   999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
949  1000  8b756f6231DDC6e        Lee      Tran  Female   

    douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0           pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1      dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2      ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3     carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4     fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   
..                           ...                     ...         ...   
945       lyonsdaisy@example.net            021.775.2933  05-01-1959   
946      dariusbryan@example.com    001-149-710-7799x721  06-10-2001   
947       georgechan@example.org   +1-750-774-4128x33265  13-05-1918   
948          wanda04@example.net           (915)292-2254  31-08-1971   
949      deannablack@example.org      079.752.5424x67259  24-01-1947   

             Human resources officer   70000  
0                       Nurse, adult   80000  
1                Seismic interpreter   70000  
2                          Barrister   60000  
3               Engineer, structural  100000  
4                    Producer, radio   50000  
..                               ...     ...  
945                Personnel officer   90000  
946          Education administrator   50000  
947  Commercial/residential surveyor   60000  
948                 Ambulance person  100000  
949       Nurse, learning disability   90000  

[950 rows x 10 columns]

In [121]:
# b) Only read the specified columns
selected_columns = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
df = df[selected_columns]

In [116]:
# c) Display the first 10 rows of the filtered dataset
print("First 10 rows of the filtered dataset:")
print(df.head(10))

First 10 rows of the filtered dataset:
  Last Name  Gender                       Email                   Phone  \
0    Zavala    Male        pamela64@example.net  001-859-448-9935x54536   
1     Carey  Female   dianashepherd@example.net    001-274-739-8470x814   
2     Hobbs  Female   ingramtiffany@example.org        241.179.9509x498   
3    Reilly    Male  carriecrawford@example.org       207.797.8345x6177   
4    Conrad    Male  fuentesclaudia@example.net    001-599-042-7428x143   
5      Cole    Male      kaneaudrey@example.org            663-280-5834   
6   Donovan    Male   rebekahsantos@example.net                     NaN   
7    Little  Female         craig28@example.com       125.219.3673x0076   
8    Dawson  Female  connercourtney@example.net      650-748-3069x64529   
9      Page    Male  harrygallagher@example.com        849.500.6331x717   

   Salary  
0   80000  
1   70000  
2   60000  
3  100000  
4   50000  
5   85000  
6   65000  
7   60000  
8   60000  
9   60000  


In [118]:
# d) Extract the ‘Salary’ column as a Series and display its last 5 values
salary_series = df['Salary']
print("\nLast 5 values of the 'Salary' column:")
print(salary_series.tail(5))


Last 5 values of the 'Salary' column:
945     90000
946     50000
947     60000
948    100000
949     90000
Name: Salary, dtype: int64


## Que 9.
### Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke','Gender' column contains the word Female and ‘Salary’ should Be less than 85000.

In [128]:
df = pd.read_csv(r"E:\DataScience\Assignment\People Data.csv")
# Filter and select rows based on conditions
filtered_df = df[(df['Last Name'].str.contains('Duke')) & 
                 (df['Gender'] == 'Female') & 
                 (df['Salary'] < 85000)]

# Display the filtered DataFrame
pd.DataFrame(filtered_df)

Index          User Id First Name Last Name  Gender  \
45      46  99A502C175C4EBd     Olivia      Duke  Female   
210    211  DF17975CC0a0373    Katrina      Duke  Female   
457    458  dcE1B7DE83c1076      Traci      Duke  Female   
729    730  c9b482D7aa3e682     Lonnie      Duke  Female   

                        Email                   Phone Date of birth  \
45        diana26@example.net  001-366-475-8607x04350    13-10-1934   
210       robin78@example.com            740.434.0212    21-09-1935   
457  perryhoffman@example.org     +1-903-596-0995x489    11-02-1997   
729   kevinkramer@example.net            982.692.6257    12-05-2015   

           Job Title  Salary  
45           Dentist   60000  
210  Producer, radio   50000  
457        Herbalist   50000  
729     Nurse, adult   70000

## Que 10.
###  Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 t 6

In [139]:
Randomint = np.random.randint(1,7,35) #generating random number
print("Random Generated Number :",Randomint)
df = pd.DataFrame(Randomint.reshape(7,5))
print("\n(7*5) DataFrame using pandas :")
df

Random Generated Number : [4 3 6 5 3 3 3 1 4 1 4 6 1 3 4 6 5 3 2 4 3 1 1 1 3 1 5 2 6 1 2 3 6 2 3]

(7*5) DataFrame using pandas :


0  1  2  3  4
0  4  3  6  5  3
1  3  3  1  4  1
2  4  6  1  3  4
3  6  5  3  2  4
4  3  1  1  1  3
5  1  5  2  6  1
6  2  3  6  2  3